// Generated by tools/optimize-images.mjs — do not edit by hand.
window.AURIQUE_GALLERY = [
  {
    "id": "builder-gel-long__aqua-aura",
    "service": "builder-gel-long",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel-long__aqua-aura-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel-long__aqua-aura-600.webp 600w, assets/img/gallery/manicure/builder-gel-long__aqua-aura-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "builder-gel-long__black-almond",
    "service": "builder-gel-long",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel-long__black-almond-1200.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel-long__black-almond-600.webp 600w, assets/img/gallery/manicure/builder-gel-long__black-almond-1200.webp 1200w",
    "w": 1306,
    "h": 1336
  },
  {
    "id": "builder-gel-long__green-cat-eye",
    "service": "builder-gel-long",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel-long__green-cat-eye-1200.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel-long__green-cat-eye-600.webp 600w, assets/img/gallery/manicure/builder-gel-long__green-cat-eye-1200.webp 1200w",
    "w": 1262,
    "h": 1600
  },
  {
    "id": "builder-gel-long__nude-chrome-tips",
    "service": "builder-gel-long",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel-long__nude-chrome-tips-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel-long__nude-chrome-tips-600.webp 600w, assets/img/gallery/manicure/builder-gel-long__nude-chrome-tips-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "builder-gel__burgundy-almond",
    "service": "builder-gel",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel__burgundy-almond-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel__burgundy-almond-600.webp 600w, assets/img/gallery/manicure/builder-gel__burgundy-almond-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "builder-gel__french-floral-accent",
    "service": "builder-gel",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel__french-floral-accent-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel__french-floral-accent-600.webp 600w, assets/img/gallery/manicure/builder-gel__french-floral-accent-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "builder-gel__red-polka-dots",
    "service": "builder-gel",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel__red-polka-dots-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel__red-polka-dots-600.webp 600w, assets/img/gallery/manicure/builder-gel__red-polka-dots-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "builder-gel__violet-chrome-tips",
    "service": "builder-gel",
    "cat": "manicure",
    "src": "assets/img/gallery/manicure/builder-gel__violet-chrome-tips-900.webp",
    "srcset": "assets/img/gallery/manicure/builder-gel__violet-chrome-tips-600.webp 600w, assets/img/gallery/manicure/builder-gel__violet-chrome-tips-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "gel-pedicure__pearl-white",
    "service": "gel-pedicure",
    "cat": "pedicure",
    "src": "assets/img/gallery/pedicure/gel-pedicure__pearl-white-900.webp",
    "srcset": "assets/img/gallery/pedicure/gel-pedicure__pearl-white-600.webp 600w, assets/img/gallery/pedicure/gel-pedicure__pearl-white-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "extensions__color-swirls",
    "service": "extensions",
    "cat": "extensions",
    "src": "assets/img/gallery/extensions/extensions__color-swirls-900.webp",
    "srcset": "assets/img/gallery/extensions/extensions__color-swirls-600.webp 600w, assets/img/gallery/extensions/extensions__color-swirls-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "extensions__dotted-outline",
    "service": "extensions",
    "cat": "extensions",
    "src": "assets/img/gallery/extensions/extensions__dotted-outline-900.webp",
    "srcset": "assets/img/gallery/extensions/extensions__dotted-outline-600.webp 600w, assets/img/gallery/extensions/extensions__dotted-outline-900.webp 900w",
    "w": 900,
    "h": 1600
  },
  {
    "id": "extensions__long-french",
    "service": "extensions",
    "cat": "extensions",
    "src": "assets/img/gallery/extensions/extensions__long-french-899.webp",
    "srcset": "assets/img/gallery/extensions/extensions__long-french-600.webp 600w, assets/img/gallery/extensions/extensions__long-french-899.webp 899w",
    "w": 899,
    "h": 1600
  },
  {
    "id": "extensions__silver-chrome-swirls",
    "service": "extensions",
    "cat": "extensions",
    "src": "assets/img/gallery/extensions/extensions__silver-chrome-swirls-900.webp",
    "srcset": "assets/img/gallery/extensions/extensions__silver-chrome-swirls-600.webp 600w, assets/img/gallery/extensions/extensions__silver-chrome-swirls-900.webp 900w",
    "w": 900,
    "h": 1600
  }
];
